---

- name: Create kubelet systemd dropin directory
  file: path="{{ systemd_dropin_dir }}/kubelet.service.d" state=directory

- name: Copy kubelet dropin file into directory
  template:
    src: "10-kubelet.conf.j2"
    dest: "{{ systemd_dropin_dir }}/kubelet.service.d/10-kubelet.conf"

- name: Copy kubelet systemd service file
  template:
    src: "kubelet.service.j2"
    dest: "{{ systemd_service_dir }}/kubelet.service"
    owner: root
    group: root
    mode: 0644

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: service_started
