---

- when: node_role == 'master'
  include_tasks: setup-masters.yml

- include_tasks: setup-nodes.yml

- include_tasks: config-systemd.yml

- name: Wait for Kubernetes core component start
  when: node_role == 'master'
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 1
    connect_timeout: 60
    timeout: 300
  with_items:
    - "{{ apiserver_secure_port }}"
    - "{{ lb_secure_port }}"
    - "10252"
    - "10251"

- when: node_role == 'master'
  include_tasks: setup-resources.yml

- name: Set taint gpu-node to effect NoSchedule
  when: node_role == 'node' and container_runtime == 'nvidia-docker'
  command: |
    {{ bin_dir }}/kubectl --kubeconfig={{ admin_kubeconfig }} \
      taint nodes {{ ansible_hostname }} nvidia.com/gpu="":NoSchedule --overwrite
  delegate_to: "{{ groups['masters'][0] }}"
  register: set_taint
  until: set_taint.rc == 0
  retries: 10
  delay: 2
  ignore_errors: true
