---
- name: test
  shell: ls {{ etcd_ca }}

- name: read pem files
  command: cat {{ etcd_ca }}
  register: ca

- name: read pem files
  command: cat {{ etcd_cert }}
  register: cert

- name: read pem files
  command: cat {{ etcd_cert_key }}
  register: key

- name: "Ensure cronjob directory exists"
  file: path="{{ cronjob_dir }}" state=directory

- name: copy etcd_backup
  template:
    src: "etcd-backup.yml.j2"
    dest: "{{ cronjob_dir }}/etcd-backup.yml"

- name: copy etcd_backup
  template:
    src: "etcd-backup.yml.j2"
    dest: "{{ cronjob_dir }}/etcd-backup.yml"

- name: "Apply etcd backup job"
  command: |
    {{ bin_dir }}/kubectl --kubeconfig={{ admin_kubeconfig }} \
      apply -f {{ cronjob_dir }}/etcd-backup.yml