---
    
- name: select docker container
  when: "container_runtime != 'containerd'"
  shell: 'lspci | grep NVIDIA'
  register: result 
  ignore_errors: true

- when:
    - "container_runtime  != 'containerd'"
    - result.stdout != ''  
  set_fact:
    container_runtime: 'nvidia-docker'
