#!/bin/bash

repo="{{ localrepo }}"
files=`find .. -name '*.j2'`

basepath=$(cd `dirname $0`; pwd)
echo $basepath

for f in ${files}
do
  echo $f $repo
  python  ${basepath}/offline-tools/change_images_repo_to_local.py -f "${f}" -r "${repo}"
done
