#!/bin/bash

basepath=$(cd `dirname $0`; pwd)

repo="{{ localrepo }}"
files=`find $basepath/.. -name '*.j2'`

echo $basepath

for f in ${files}
do
  echo $f $repo
  python  ${basepath}/offline-tools/change_images_repo_to_local.py -f "${f}" -r "${repo}"
done
