---

- name: Copy Docker environment config file
  template: src=docker/docker.env.j2 dest={{ systemd_env_dir }}/docker

- name: Add any insecure registrys to Docker config
  when: insecure_registrys is defined and insecure_registrys > 0
  lineinfile:
    dest: "{{ systemd_env_dir }}/docker"
    regexp: "^INSECURE_REGISTRY="
    line: 'INSECURE_REGISTRY="{% for reg in insecure_registrys %}--insecure-registry={{ reg }} {% endfor %}"'

- name: Add registry to Docker config
  when: add_registry is defined and add_registry > 0
  lineinfile:
    dest: "{{ systemd_env_dir }}/docker"
    regexp: "^ADD_REGISTRY= "
    line: 'ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"'

- name: Add extra options to Docker config
  when: docker_opts is defined and docker_opts > 0
  lineinfile:
    dest: "{{ systemd_env_dir }}/docker"
    regexp: "^DOCKER_OPTS= "
    line: 'DOCKER_OPTS="{% for opt in docker_opts %}{{ opt }} {%endfor %}"'
