---

kube_version: 1.14.3

# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker

# Container network,
# Supported: calico, flannel, sriov, multus, hca.
cni_enable: true
container_network: calico

# Kubernetes HA extra variables.
vip_interface: ""
vip_address: 172.16.35.9

# Kubernetes extra addons
enable_ingress: false
enable_dashboard: false
enable_logging: false
enable_monitoring: false
enable_metric_server: false
enable_nfs_client: false
enable_rdma_nfs_client: false
enable_helm: false
enable_external_dns: false

ingress_domain: "k8s.local"

monitoring_grafana_user: "admin"
monitoring_grafana_password: "p@ssw0rd"

storages:
  nfs:
    name: "nfs-client-provisioner"
    provisioner: "fuseim.pri/ifs"
    nfs_server: "192.168.21.29"
    nfs_path: "/var/nfs/home"
    nfs_storage_class: "nfs"

backup:
  etcd:
    storage_class_name: "nfs"
    storage_size: "10Gi"

logging:
  kibana:
    ingress_host: "kibana.{{ ingress_domain }}"
  elasticsearch:
    storage_class_name: "nfs"
    storage_size: "200Gi"

monitoring:
  prometheus:
    ingress_host: "prometheus.{{ ingress_domain }}"
  grafana:
    ingress_host: "grafana.{{ ingress_domain }}"

external_dns:
  dns_vip: {{ vip_address }}
