---

bin_dir: /usr/local/bin
sbin_dir: /usr/local/sbin
cache_dir: /tmp
ld_config_dir: /etc/ld.so.conf.d

systemd_service_dir: /lib/systemd/system
systemd_env_dir: /etc/default
systemd_dropin_dir: /etc/systemd/system

docker_data_dir: /var/lib/docker
docker_config_dir: /etc/docker
nvidia_runtime_config_dir: /etc/nvidia-container-runtime
libnvidia_header_file: /usr/local/include/nvc.h
libnvidia_lib_dir: /usr/local/lib/libnvidia
containerd_data_dir: /var/lib/containerd
containerd_config_dir: /etc/containerd
